### PR TITLE
Update dev requirements

### LINKED ISSUE #121: Bump requests to 2.31.0
A requests bug was found: [GHSA-j8r2-6x86-q33q](https://github.com/psf/requests/security/advisories/GHSA-j8r2-6x86-q33q)

We're not directly affected AFAICT but bumping the version in next release is no harm.

Diff review is done in https://github.com/freedomofpress/securedrop/issues/6820

### PR DESCRIPTION
**Pull request by rocodes**
Closes #121 

Update dev requirements:
- [ ] CI is passing and bullseye / bookworm are compiled with python 3.9 / 3.11 respectively
- [ ] Visual review is reasonable

(edit: update to `black` means there are additional formatting changes that have been applied too)

### CODE REVIEW

**Comment by rocodes** [comment]
Might need to revisit the `make update-dev-only-dependencies` workflow.

Linting is failing even though `make check-black lint` succeeds locally :/

```
$ make check-black lint
All done! ✨ 🍰 ✨
29 files would be left unchanged.
flake8 securedrop_export/ tests/
```

check-testing-requirements is failing due to a difference with pip and setuptools being pulled in, I'll look at it

**Comment by legoktm** [comment]
Did you reset your virtualenv after bumping the dependencies? When I check this out and run `make black`, it fixes a bunch of stuff:
```
(.venv)user@dev ~/g/f/securedrop-export> make black
reformatted /home/user/github/freedomofpress/securedrop-export/securedrop_export/disk/legacy_status.py
reformatted /home/user/github/freedomofpress/securedrop-export/securedrop_export/disk/status.py
reformatted /home/user/github/freedomofpress/securedrop-export/securedrop_export/print/status.py
reformatted /home/user/github/freedomofpress/securedrop-export/securedrop_export/disk/service.py
reformatted /home/user/github/freedomofpress/securedrop-export/securedrop_export/disk/volume.py
reformatted /home/user/github/freedomofpress/securedrop-export/tests/test_directory.py
reformatted /home/user/github/freedomofpress/securedrop-export/tests/test_main.py
reformatted /home/user/github/freedomofpress/securedrop-export/tests/disk/test_cli.py
reformatted /home/user/github/freedomofpress/securedrop-export/tests/print/test_service.py
```

**Comment by rocodes** [comment]
Evidently I did not :facepalm: thanks - pushed

**Comment by rocodes** [comment]
Thought I had, but evidently had not.  That's embarrassing!

Re: the `check testing requirements`, do you see what I'm missing here?  "Expected" does not include `requirements/requirements.in` in the pip-compile command for generating bookworm dependencies, "actual" does include it. (requirements.in is empty, anyway, but it seems like one would want to include it when generating requirements).

Sorry if this is all fairly obvious.

**Comment by legoktm** [comment]
It should match the output of `make requirements`... when I run that locally I get the same diff:
```
diff --git a/requirements/dev-bookworm-requirements.txt b/requirements/dev-bookworm-requirements.txt
index 703eddf..30a761a 100644
--- a/requirements/dev-bookworm-requirements.txt
+++ b/requirements/dev-bookworm-requirements.txt
@@ -2,7 +2,7 @@
 # This file is autogenerated by pip-compile with Python 3.11
 # by the following command:
 #
-#    pip-compile --allow-unsafe --generate-hashes --output-file=requirements/dev-bookworm-requirements.txt requirements/dev-bookworm-requirements.in requirements/requirements.in
+#    pip-compile --allow-unsafe --generate-hashes --output-file=requirements/dev-bookworm-requirements.txt requirements/dev-bookworm-requirements.in
 #
```

So either `requirements/requirements.in` should be added to the pip-compile commands that `make requirements` runs or it shouldn't be in the `dev-*-requirements.txt` file...

(this will all go away once we poetry, I hope!)

**Comment by rocodes** [comment]
Man I'm suffering here :joy:   But we're close:

```
# make venv && make requirements && git diff --exit-code 0 requirements/dev-bullseye-requirements.txt 
[snip]
-pip==23.1.2 \
-    --hash=sha256:0e7c86f486935893c708287b30bd050a36ac827ec7fe5e43fe7cb198dd835fba \
-    --hash=sha256:3ef6ac33239e4027d9a5598a381b9d30880a1477e50039db2eac6e8a8f6d1b18
-    # via pip-tools
 pip-tools==6.13.0 \
     --hash=sha256:50943f151d87e752abddec8158622c34ad7f292e193836e90e30d87da60b19d9 \
     --hash=sha256:61d46bd2eb8016ed4a924e196e6e5b0a268cd3babd79e593048720db23522bb1
@@ -442,10 +438,6 @@ semgrep==1.28.0 \
     --hash=sha256:e1356313a78cca7ebf5b37b52840cc4420b5111321bc5c54830d5187b6789fc1 \
     --hash=sha256:fe182404f64ab1c243cd23f2991ad956e555ce42bc2e3d421e08bbc703c43eb8
     # via -r requirements/dev-bullseye-requirements.in
-setuptools==68.0.0 \
-    --hash=sha256:11e52c67415a381d10d6b462ced9cfb97066179f0e871399e006c4ab101fc85f \
-    --hash=sha256:baf1fdb41c6da4cd2eae722e135500da913332ab3f2f5c7d33af9b492acb5235
-    # via pip-tools
 tomli==2.0.1 \
     --hash=sha256:939de3e7a6161af0c887ef91b7d41a53e7c5a1ca976325f429cb46ea9bc30ecc \
     --hash=sha256:de526c12914f0c550d15924c62d72abc48d6fe7364aa87328337a31007fe8a4f
@@ -545,3 +537,13 @@ wheel==0.40.0 \
     --hash=sha256:cd1196f3faee2b31968d626e1731c94f99cbdb67cf5a46e4f5656cbee7738873 \
     --hash=sha256:d236b20e7cb522daf2390fa84c55eea81c5c30190f90f29ae2ca1ad8355bf247
     # via pip-tools
+
+# The following packages are considered to be unsafe in a requirements file:
+pip==23.1.2 \
+    --hash=sha256:0e7c86f486935893c708287b30bd050a36ac827ec7fe5e43fe7cb198dd835fba \
+    --hash=sha256:3ef6ac33239e4027d9a5598a381b9d30880a1477e50039db2eac6e8a8f6d1b18
+    # via pip-tools
+setuptools==68.0.0 \
+    --hash=sha256:11e52c67415a381d10d6b462ced9cfb97066179f0e871399e006c4ab101fc85f \
+    --hash=sha256:baf1fdb41c6da4cd2eae722e135500da913332ab3f2f5c7d33af9b492acb5235
+    # via pip-tools

Exited with code exit status 1

```
So the requirements are the same, but difference in how the `unsafe` packages (pip, setuptools) are displayed in the output is causing an issue here.

(There are lots of upstream reports trying to decide how to handle `unsafe` packages. see eg https://github.com/jazzband/pip-tools/issues/1655 for a slightly related problem)

**Comment by legoktm** [comment]
I vaguely remember that being a behavioral change in pip-compile...double check the same version is being used in both places?

**Comment by rocodes** [comment]
:thinking: I recall the same thing, but

```
user@sd-dev:~/projects/securedrop-export$ source .venv311/bin/activate
(.venv311) user@sd-dev:~/projects/securedrop-export$ pip-compile --version
pip-compile, version 6.13.0
(.venv311) user@sd-dev:~/projects/securedrop-export$ deactivate
user@sd-dev:~/projects/securedrop-export$ source .venv/bin/activate
(.venv) user@sd-dev:~/projects/securedrop-export$ pip-compile --version
pip-compile, version 6.13.0
(.venv) user@sd-dev:~/projects/securedrop-export$ 
```

**Review by eaon — APPROVED** [review]
Thank you!

(Also ha, lots of lines for just a dev requirements update… technology :woozy_face:)

**Pull request merged**
