### PR TITLE
Removes mimetype associations

### PR DESCRIPTION
**Pull request by conorsch**
As part of template consolidation [0], we're moving mimetype
associations out of system volumes and into private volumes. Therefore
we no longer need these files in the 'securedrop-export' package, as the
corresponding files have already been ported to
'securedrop-workstation-config'.

[0] https://github.com/freedomofpress/securedrop-workstation/issues/471

Packaging changes are in https://github.com/freedomofpress/securedrop-debian-packaging/pull/198

### CODE REVIEW

**Comment by emkll** [comment]
Changes here look good to me , and good to merge after dropping the temporary commit

**Comment by conorsch** [comment]
Rebased to include #64

**Comment by conorsch** [comment]
Dropped temporary commit. That means CI will fail here until https://github.com/freedomofpress/securedrop-debian-packaging/pull/198 is merged, so let's get that one in first, then re-run CI here to confirm everything's green.

**Review by emkll — APPROVED** [review]
Restarted CI, now passing (see https://app.circleci.com/pipelines/github/freedomofpress/securedrop-export/196/workflows/7f5f0b79-74ba-4280-a027-9b64e2923e65/jobs/522)

**Pull request merged**
