### PR TITLE
Change driver/PPD used for Brother printers

### PR DESCRIPTION
**Pull request by rmol**
Fixes https://github.com/freedomofpress/securedrop-workstation/issues/506, or at least makes it possible to print the image that prompted the issue, and continues to print other file types as well.

### CODE REVIEW

**Comment by emkll** [comment]
Also experiencing some issues with the changes introduced here. I built the securedrop-export package and installed it in sd-devices. When sending a device to the printer, `sdw-printer` comes up as a LaserJet printer. However, I cannot print _any_ documents. I tried:
- .docx
- .pdf
- .jpg
- .gif

The ready light flashes for ~10 seconds and then becomes solid again for pdf, jpg and pdf, and stuck at 'processing' for docx.

xpp_cups

**Comment by eloquence** [comment]
Moving this back to backlog for now. We'll revisit printer issues after the first release.

**Comment by eloquence** [comment]
(Adding to "Discussion Points" to check in on status of this PR.)

**Comment by eloquence** [comment]
Given the inconsistent reports above, we've agreed to close out this change for now; we may revisit in future in context of larger improvements to printer handling.

**Pull request closed without merging**
